### ISSUE TITLE
Error building app when asset fingerprint prepend is set

### ISSUE THREAD

**Issue by fusion2004** [gcollazo/ember-cli-showdown#66]
Hello, I am having an issue where if my app has an asset fingerprint prepend set, it gets this error while building:
```
$ ember build
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Build failed.
Build Error (AssetRewrite) in assets/vendor.js

Cannot read property '2' of null


Stack Trace and Error Report: /var/folders/sq/n70gy7gj2yl1lhdpbdsk5cf40000gn/T/error.dump.7ca510575e7a9fc80ba3a7c583c28aa2.log
```

<details>
<summary>The contents of that "Stack Trace and Error Report" file</summary>

```
=================================================================================

ENV Summary:

  TIME: Tue May 29 2018 15:04:00 GMT-0400 (EDT)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/10.2.1/bin/node
  - /usr/local/bin/ember
  - build
  EXEC_PATH: /usr/local/Cellar/node/10.2.1/bin/node
  TMPDIR: /var/folders/sq/n70gy7gj2yl1lhdpbdsk5cf40000gn/T
  SHELL: /usr/local/bin/zsh
  PATH:
  - /Users/markoleson/.rvm/gems/ruby-2.5.0/bin
  - /Users/markoleson/.rvm/gems/ruby-2.5.0@global/bin
  - /Users/markoleson/.rvm/rubies/ruby-2.5.0/bin
  - /Users/markoleson/.avn/bin
  - /Users/markoleson/.cargo/bin
  - /usr/local/heroku/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/markoleson/bin
  - /Users/markoleson/.antigen/bundles/zsh-users/zsh-syntax-highlighting
  - /Users/markoleson/.rvm/bin
  PLATFORM: darwin x64
  FREEMEM: 166084608
  TOTALMEM: 17179869184
  UPTIME: 1473985
  LOADAVG: 2.81103515625,2.53076171875,2.49755859375
  CPUS:
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.0
  - http_parser: 2.8.0
  - icu: 61.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.29.0
  - node: 10.2.1
  - openssl: 1.1.0h
  - tz: 2018c
  - unicode: 10.0
  - uv: 1.20.3
  - v8: 6.6.346.32-node.8
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property '2' of null
    at AssetRewrite.rewriteAssetPath (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-asset-rewrite/index.js:127:91)
    at AssetRewrite.processString (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-asset-rewrite/index.js:167:24)
    at AssetRewrite.processFile (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  - codeFrame: Cannot read property '2' of null
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `AssetRewrite` plugin. 💥
Cannot read property '2' of null
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: assets/vendor.js
    - line: [undefined]
    - treeDir: /Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/tmp/asset_rewrite-input_base_path-aQLdKWk2.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `AssetRewrite` plugin. 💥
Cannot read property '2' of null
  - name: Error
  - nodeAnnotation: AssetRewrite
  - nodeName: AssetRewrite
  - originalErrorMessage: Cannot read property '2' of null
  - stack: TypeError: Cannot read property '2' of null
    at AssetRewrite.rewriteAssetPath (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-asset-rewrite/index.js:127:91)
    at AssetRewrite.processString (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-asset-rewrite/index.js:167:24)
    at AssetRewrite.processFile (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/markoleson/Developer/ember-cli-showdown-asset-prepend-issue/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)

=================================================================================
```
</details>

&nbsp;
The line it is talking about causing the error is [here](https://github.com/rickharrison/broccoli-asset-rewrite/blob/212cd52d27c7174997c387f6ecc768e2ccadecf2/index.js#L127).

The value of `replaceString` looks to be:
```
assets/showdown.js-e62a355f75b7091f050b33ee62504bdb.map

}
```

I'm guessing it is not supposed to include that linebreak and `}`, but I really don't know.

I have a simple reproduction here: https://github.com/fusion2004/ember-cli-showdown-asset-prepend-issue

**Comment by jasonmit** [comment]
This should now be resolved in 4.4.3.  Thanks!
